name: TestPlugin
main: org.wochang.plugins.TestPlugin
version: 1.0
api-version: 1.16
commands:
   gift:
      description: A gift from Baba
      usage: /gift
      permission: testplugin.gift
   gohome:
      description: Teleport to your bed
      usage: /gohome
      permission: testplugin.gohome
   mkmobs:
      description: Summon lots of mobs at once
      usage: /mkmobs
      permission: testplugin.mkmobs
   clearmobs:
      description: Clear summoned mobs
      usage: /clearmobs
      permission: testplugin.clearmobs
   