name: TestPlugin
main: org.wochang.plugins.TestPlugin
version: 1.0
api-version: 1.16
commands:
   gift:
      description: A gift from Baba
      usage: /gift <playername>
      permission: testplugin.gift
   gohome:
      description: Teleport to your bed
      usage: /gohome
      permission: testplugin.gohome
   mkmob:
      description: Summon lots of mobs at once
      usage: "Usage: /mkmob mobtype [num mobs] [location]"
      permission: testplugin.mkmob
   nomob:
      description: Clear summoned mobs
      usage: /nomob
      permission: testplugin.nomob
   